In [1]:
import cv2

In [2]:
#reading image

boy_image = cv2.imread('boy.jpg')
boy_image.shape

(339, 509, 3)

In [3]:
#rendering image on display
cv2.imshow('output image', boy_image)

#creating clone of image
cv2.imwrite('boy_clone.jpg', boy_image)
cv2.imwrite('boy_clone.png', boy_image)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
#converting image from rgb to gray scale
gray_img = cv2.cvtColor(boy_image, cv2.COLOR_RGB2GRAY)

gray_img.shape

(339, 509)

In [5]:
cv2.imshow('output image', gray_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
#converting gray scale image to binary image
ret, binary_img = cv2.threshold(gray_img, 127, 255, cv2.THRESH_BINARY)

In [7]:
binary_img.shape

(339, 509)

In [8]:
cv2.imshow('binary image', binary_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
#converting image to hsv format
hsv_image = cv2.cvtColor(boy_image, cv2.COLOR_RGB2HSV)

hsv_image.shape

(339, 509, 3)

In [10]:
#image in hsv format
cv2.imshow('hsv image',hsv_image)

#only hue image
cv2.imshow('hue', hsv_image[:, :, 0])

#only saturation image
cv2.imshow('saturation', hsv_image[:, : , 1])

#only value image
cv2.imshow('value', hsv_image[:, :, 2])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
#extracting different frames from the rgb image
b, g, r = cv2.split(boy_image)

b.shape, g.shape, r.shape, boy_image.shape

((339, 509), (339, 509), (339, 509), (339, 509, 3))

In [12]:
import numpy as np

#uint8 means 8 bit unsigned integer
zero_arr = np.zeros(b.shape, dtype="uint8")

zero_arr.shape, type(zero_arr), zero_arr

((339, 509), numpy.ndarray, array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8))

In [13]:
cv2.imshow('blue frame image', cv2.merge([b, zero_arr, zero_arr]))
cv2.imshow('green frame image', cv2.merge([zero_arr, g, zero_arr]))
cv2.imshow('red frame image', cv2.merge([zero_arr, zero_arr, r]))
cv2.imshow('original image', boy_image)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
original_height, original_width = boy_image.shape[:2]
original_height, original_width

(339, 509)

In [15]:
#      | 1 0 Tx |
#  T = | 0 1 Ty |


T = np.float32([[1, 0, original_width/4],
                [0, 1, original_height/4]])

T.shape, T

((2, 3), array([[  1.  ,   0.  , 127.25],
        [  0.  ,   1.  ,  84.75]], dtype=float32))

In [16]:
translated_image = cv2.warpAffine(boy_image, T, (original_width, original_height))

cv2.imshow('original image', boy_image)
cv2.imshow('translated image', translated_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
#rotated image
rotated_image_matrix = cv2.getRotationMatrix2D((original_width/2, original_height/2), 120, .6)
rotated_image = cv2.warpAffine(boy_image, rotated_image_matrix, (original_width, original_height))

In [18]:
cv2.imshow('rotated image', rotated_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
#transpose image
transposed_image = cv2.transpose(boy_image)
cv2.imshow('transposed image', transposed_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
#image resizing
scaled_up_image = cv2.resize(boy_image, None, fx=0.5, fy=0.5)
cv2.imshow('scaled up image', scaled_up_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
scaled_down_image = cv2.resize(boy_image, None, fx=2, fy=2, interpolation=cv2.INTER_CUBIC)
cv2.imshow('scaled down image', scaled_down_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [22]:
resized_image = cv2.resize(boy_image, (900, 500), interpolation=cv2.INTER_AREA)
cv2.imshow('resized image', resized_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
#pyramid function: used to increase or decrease size of image
scaled_down_image = cv2.pyrDown(boy_image)
scaled_up_image = cv2.pyrUp(boy_image)

#show image on screen
cv2.imshow('original image', boy_image)
cv2.imshow('scaled down image', scaled_down_image)
cv2.imshow('scaled up image', scaled_up_image)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [24]:
#cropping image
start_row, start_col = int(original_height*0.25), int(original_width*0.25)
end_row, end_col = int(original_height*0.75), int(original_width*0.75)

cropped_image = boy_image[start_row:end_row, start_col:end_col]
cv2.imshow('cropped image', cropped_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [25]:
#image blurring 7*7=49
kernel = np.ones((7,7), np.float32)/49

blurred = cv2.filter2D(boy_image, -1, kernel)
cv2.imshow('blurred image', blurred)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
#box filter blur
blur_img = cv2.blur(boy_image, (3,3))
cv2.imshow('box filter', blur_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
#gaussian filter blur
gaussian_filter_blur = cv2.GaussianBlur(boy_image, (3,3), 0)
cv2.imshow('gaussian blur image', gaussian_filter_blur)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:
#median filter blur
median_filter_blur = cv2.medianBlur(boy_image, 3)
cv2.imshow('median filter blur',median_filter_blur)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
#bilateral filter blur
bilateral_filter_blur = cv2.bilateralFilter(boy_image, 9, 75, 75)
cv2.imshow('bilateral filter blur', bilateral_filter_blur)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [30]:
#Edge Detection

#laplacian algorithm
laplacian_edge_detection = cv2.Laplacian(boy_image, cv2.CV_64F)
cv2.imshow('laplacian image', laplacian_edge_detection)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [31]:
#canny algorithm for edge detection
canny_image = cv2.Canny(boy_image, 20, 200)
cv2.imshow('canny image', canny_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [32]:
#accessing camera

import cv2

cam = cv2.VideoCapture(0)

while True:
    return_val, frame = cam.read()
    cv2.imshow('frame is', frame)
    if(cv2.waitKey(1) == 13):
        break
        
cam.release()
cv2.destroyAllWindows()

In [33]:
import cv2

cam = cv2.VideoCapture(0)

if(cam.isOpened()):
    return_val, frame = cam.read()
    print(return_val)
    print(frame)
    cv2.imshow('frame',frame)
    cam.release()
    

cv2.waitKey(0)
cv2.destroyAllWindows()


True
[[[ 50  74  87]
  [ 49  68  82]
  [ 57  70  85]
  ...
  [166 166 173]
  [165 164 171]
  [167 165 172]]

 [[ 55  76  88]
  [ 60  77  90]
  [ 68  79  94]
  ...
  [165 165 171]
  [163 162 168]
  [165 162 168]]

 [[ 68  81  92]
  [ 71  82  93]
  [ 71  79  92]
  ...
  [166 166 169]
  [164 163 166]
  [165 162 165]]

 ...

 [[ 46  56  46]
  [ 47  56  46]
  [ 48  56  48]
  ...
  [ 31  54  49]
  [ 31  54  50]
  [ 31  53  49]]

 [[ 48  56  46]
  [ 46  54  45]
  [ 44  52  44]
  ...
  [ 29  53  50]
  [ 30  52  50]
  [ 29  51  49]]

 [[ 50  57  47]
  [ 49  56  47]
  [ 48  56  48]
  ...
  [ 24  48  46]
  [ 27  50  49]
  [ 29  51  50]]]


In [34]:
#edge detection using webcam

import cv2

cam = cv2.VideoCapture(0)

while True:
    
    return_val, frame = cam.read()
    canny_edge_video = cv2.Canny(frame, 50, 170)
    cv2.imshow('real video', frame)
    cv2.imshow('canny edge detection on video', canny_edge_video)
    if(cv2.waitKey(1) == 13):
        break;
        
cam.release()
cv2.destroyAllWindows()

In [35]:
#original image, gray scale image, black & white image and sketch in real time
import cv2

cam = cv2.VideoCapture(0)

while True:
    return_val, frame = cam.read()
    cv2.imshow('frame', frame)
    
    gray_scale_video = cv2.cvtColor(frame, cv2.COLOR_RGB2GRAY)
    cv2.imshow('gray scale video', gray_scale_video)
    
    ret, binary_video = cv2.threshold(gray_scale_video, 127, 255, cv2.THRESH_BINARY)
    cv2.imshow('black and white video', binary_video)
    
    sketch_video = cv2.Canny(frame, 50, 170)
    cv2.imshow('sketch', sketch_video)
    
    if(cv2.waitKey(1) == 13):
        break

cam.release()
cv2.destroyAllWindows()

In [40]:
import cv2

rotation_matrix = cv2.getRotationMatrix2D((original_width, original_height), 45, 1)
rotated_image = cv2.warpAffine(boy_img, rotation_matrix, (original_width, original_height))
cv2.imshow('rotated image', rotated_image)

cv2.waitKey(0)
cv2.destroyAllWindows()
                                        

In [ ]:
import cv2

cam = cv2.VideoCapture(0)

while True: 
    ret, frame = cam.read()
    cv2.imshow('live cam', frame)
    if(cv2.waitKey(1) == 13):
        break;
        
cam.release()
cv2.destroyAllWindows()

### Mediapipe for hand recognition

In [ ]:
import cv2
import mediapipe as mp


class DetectHand:
    
    def __init__(self):
        self.mpHands = mp.solutions.hands
    
        #identifying hand and detecting palm and tracking it with 0.6 confidence value
        self.hands = self.mpHands.Hands(max_num_hands=1, min_detection_confidence=0.8, min_tracking_confidence=0.8)

        #getting tools to draw point and connecting line
        self.mpDraw = mp.solutions.drawing_utils

    def detectHand(self, camFrame, camFrameRGB):
    
        self.detectedHand = self.hands.process(camFrameRGB)
        
        #if hand detected then multi_hand_landmarks return coodinates of each hand point else it returns None
        if self.detectedHand.multi_hand_landmarks:
            for eachHand in self.detectedHand.multi_hand_landmarks:                    
                self.mpDraw.draw_landmarks(camFrame, eachHand, self.mpHands.HAND_CONNECTIONS)
    
        return camFrame
    
    def getHandPosition(self, camFrame):
        
        landMark = []
        if self.detectedHand.multi_hand_landmarks:
            
            for eachHand in self.detectedHand.multi_hand_landmarks:
                
                for id, lm in enumerate(eachHand.landmark):
                    
                    cam_height, cam_width, channel = camFrame.shape
                    
                    x_pixel = cam_width * lm.x
                    y_pixel = cam_height * lm.y
                    
                    landMark.append([id, x_pixel, y_pixel])
        return landMark
    
def main():
    cam = cv2.VideoCapture(0)
    
    detectHandInstance = DetectHand()
    
    while True:
    
        isCamWorking, frame = cam.read()    
    
        if(isCamWorking):
            
            #converting bgr to rgb as mp works with rgb image only
            frameRGB = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            
            frame = detectHandInstance.detectHand(frame, frameRGB)
            handPosition = detectHandInstance.getHandPosition(frameRGB)
            
            if(len(handPosition) != 0):
                
                #x-ref
                index_top_x = handPosition[8][1]
                wrist_x = handPosition[0][1]
                
            cv2.imshow('Frame', frame)
        
            if(cv2.waitKey(1) == 13):
                break;
        
        else:
            print('error in reading cam')
            break;

    cam.release()
    
    cv2.destroyAllWindows()
    
if __name__ == "__main__":
    main()